### ISSUE TITLE
Silly but important. How to discover your addon.

### ISSUE THREAD

**Issue by n-pigeon** [imjp94/gd-YAFSM#4]
Your plugin is hard to find or discover due to its... unique name ;)
If you type "state machine" in Godot Asset browser search your plugin will not pop-up.

Maybe add: gd-YAFSM (Visual State Machine) or something ;)

I found your add-on by accident browsing manually all plugins :P

PS
Your add-on looks amazing. Great job my dude!

**Comment by imjp94** [comment]
Couldn't agree more, I always have to explicitly describe what it is when I share it on twitter/youtube. 
The suggested approach is great and I will submit the edit to asset library later.

Thank you for the suggestion!

**Comment by imjp94** [comment]
Name of this plugin has been changed to ["gd-YAFSM(Finite State Machine)" on Asset Library](https://godotengine.org/asset-library/asset/817)
