### ISSUE TITLE
StateMachinePlayer node not showing up

### ISSUE THREAD

**Issue by zhannahz** [imjp94/gd-YAFSM#43]
Hi, first thank you so much for the tool! I downloaded it from the library and tried using it. However, I stuck at the step of creating a StateMachinePlayer node. This option doesn't show up when I create a new node within the addons folder, and your GitHub readme doesn't seem to provide information on that. What did I miss here? Thanks!!

**Comment by imjp94** [comment]
Have you activate the plugin in Project > Settings > Plugins?
