### ISSUE TITLE
When I enabled snap and show grid, Godot run very slowly.

### ISSUE THREAD

**Issue by DSPerson** [imjp94/gd-YAFSM#52]

**Comment by imjp94** [comment]
The graph editor has been reworked by @farfalk , but I have never experience any lag while testing.
@DSPerson do you mind uploading a video? And maybe include the version of Godot

**Comment by farfalk** [comment]
@imjp94 probably it's the antialias setting @adamscott suggested to turn to false. But with that set to false, the grid glitches or disappears while moving and zooming on some screen/resolution combinations

**Comment by DSPerson** [comment]
godot version 4.0.1 
macOS 
1. macbook Pro 2015 16G
2. macbook M1 16G
same question
https://user-images.githubusercontent.com/17868782/236449616-fbddad90-c43a-422e-b4c1-c9f4016c9f25.mov

**Comment by imjp94** [comment]
@DSPerson thanks for the info!

Can you try pasting this code to `addons/imjp94.yafsm/scenes/flowchart/FlowChartGrid.gd`?
```gdscript
extends Control

var flowchart
	
func _ready():
    flowchart = get_parent().get_parent()
    queue_redraw()

func _draw():
    self.position = flowchart.position
    self.size = flowchart.size*100  # good with min_zoom = 0.5 e max_zoom = 2.0

    # Original Draw in FlowChart.gd inspired by:
	# https://github.com/godotengine/godot/blob/6019dab0b45e1291e556e6d9e01b625b5076cc3c/scene/gui/graph_edit.cpp#L442

    var zoom = flowchart.zoom
    var snap = flowchart.snap

    var offset = -Vector2(1, 1)*10000  # good with min_zoom = 0.5 e max_zoom = 2.0
    var corrected_size = size/zoom

    var from = (offset / float(snap)).floor()
    var l = (corrected_size / float(snap)).floor() + Vector2(1, 1)

    var grid_minor = flowchart.grid_minor_color
    var grid_major = flowchart.grid_major_color

    # for (int i = from.x; i < from.x + len.x; i++) {
    for i in range(from.x, from.x + l.x):
        var color

        if (int(abs(i)) % 10 == 0):
            color = grid_major
        else:
            color = grid_minor

        var base_ofs = i * snap
        draw_line(Vector2(base_ofs, offset.y), Vector2(base_ofs, corrected_size.y), color, -1)

    # for (int i = from.y; i < from.y + len.y; i++) {
    for i in range(from.y, from.y + l.y):
        var color;

        if (int(abs(i)) % 10 == 0):
            color = grid_major
        else:
            color = grid_minor

        var base_ofs = i * snap
        draw_line(Vector2(offset.x, base_ofs), Vector2(corrected_size.x, base_ofs), color, -1)
```

According to @farfalk, it should be faster but glitchy. But somehow it works fine for me, let me know if it works for you too.
![ezgif-5-a1c46458ee](https://user-images.githubusercontent.com/11486079/236490861-c7f2d442-7b69-40ce-afce-2daa5ecb92f2.gif)

**Comment by DSPerson** [comment]
@farfalk Nice! you fixed this bug,  and zoom is worked

https://user-images.githubusercontent.com/17868782/236593099-ddcd2634-726c-4d02-8749-ee36ccd002c4.mov

**Comment by DSPerson** [comment]
@farfalk I'd like to make an opinion, I must drag this scroll indicator to move , and i can't use my mac touch table to zoom
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/17868782/236593236-e9c8c714-efa2-440a-b092-a6eaffd7fca4.png">

**Comment by DSPerson** [comment]
I founded another bug, I can't delete state when i click delete key, in my video, i click delete key many times, but not work, I don't know why.
so, i add a delete action in pop menu when i click right button.

https://user-images.githubusercontent.com/17868782/236596560-e99bde8b-3ae7-4418-ae5c-bedb1adc9763.mov

**Comment by farfalk** [comment]
@imjp94 and @DSPerson I opened #54 to address what has been reported :) check that out

**Comment by farfalk** [comment]
> @farfalk I'd like to make an opinion, I must drag this scroll indicator to move , and i can't use my mac touch table to zoom <img alt="image" width="1345" src="https://user-images.githubusercontent.com/17868782/236593236-e9c8c714-efa2-440a-b092-a6eaffd7fca4.png">

(I'm not addressing this in #54, mostly because I don't know what solution to propose)
