### ISSUE TITLE
Transitions are not deleted properly

### ISSUE THREAD

**Issue by SirPigeonz** [imjp94/gd-YAFSM#6]
I found out that even with delete transitions are not properly removed from the resource :D

Test Project:
[gd-YAFSM_test.zip](https://github.com/imjp94/gd-YAFSM/files/5990608/gd-YAFSM_test.zip)

How to reproduce:
- remove Transition from State2 to State3
- change node
- or Run the Scene and check console

What happens:
Transition is back.

I also have other project where I deleted even the state that connects transitions and even if in the visual editor both are gone, the game acts like they are still there.
Probably they are not properly removed in the resource.

**Comment by imjp94** [comment]
Hmm... It works for me as shown in the [video](https://user-images.githubusercontent.com/11486079/108104513-5e212c80-70c6-11eb-8ce1-dd2690ecfdd0.mp4) attached, am I missing anything?

**Comment by SirPigeonz** [comment]
Ah... weird... State2 and State3 work for me too.
State3 and State1 transition is broken for some reason. Maybe it is related to saving resource to a file?

**Comment by imjp94** [comment]
I got it! Another corrupted resource...
The keys of `StateMachine.transitions` dictionary doesn't match with `Transition.from/to`

`StateMachine` shows that State3 connecting to State:
![Screenshot 2021-02-17 040956](https://user-images.githubusercontent.com/11486079/108116089-0ab6da80-70d6-11eb-81ce-fe793abf6acd.png)
While `Transition` resource shows that State3 is connecting to State1:
![Screenshot 2021-02-17 041237](https://user-images.githubusercontent.com/11486079/108116362-6719fa00-70d6-11eb-8261-e5836d6d5f26.png)

Do you still happen to remember how to reproduce the same bug?

**Comment by SirPigeonz** [comment]
Unfortunately I have no idea :(
I will keep a close eye on this in case I'll stumble on it again.

**Comment by imjp94** [comment]
I guess it's pretty random, but that's fine, I will be adding a `validate()` function to inspect and fix potential error whenever a StateMachine resource is loaded, which could even prevent bug like #5.

**Comment by SirPigeonz** [comment]
Awesome :)

BTW
I'm using your add-on for a small project of mine, and it is incredibly useful in so many places! I don't understand why core devs refuse to have FSM in vanilla Godot like it is a corner case tool...
Again, thx for developing this :)
