### ISSUE TITLE
An error for StateDictionary class

### ISSUE THREAD

**Issue by dawnrs** [imjp94/gd-YAFSM#70]
Test Code:
```
var s = "App/Game/Playing"
var dir = StateDirectory.new(s)
print(dir.next())
print(dir.next())
print(dir.next())
print(dir.next())
```
Output:
```
App
p/Game
e/Playing
<null>
```

Plugin Code：
https://github.com/imjp94/gd-YAFSM/blob/36fe340f27252e157fa1de2c96caf72787c656ef/addons/imjp94.yafsm/src/StateDirectory.gd#L63
I suppose at the end of this line it might be “-1” (not +1)

**Comment by imjp94** [comment]
The fix has been merged, thank you!
