### ISSUE TITLE
Could not resolve class "res://addons/iomjp94.yafsm/src/StackPlayer.gd"

### ISSUE THREAD

**Issue by tayete** [imjp94/gd-YAFSM#74]
After several weeks working perfectly, suddenly this morning this error appeared at (0,0) in StateMachinePlayer.gd and doesn't allow the addon to work. All the scripts from the addon node have turned their icons in the scenes from blue which were before, to white. The StateMachine panel shows no grid nor charts.
I have tried reinstalling, deleting all the YAFSM nodes and trying to recreate them, to no avail. Even restoring older backups which worked perfectly, don't work any more.

I am using Godot 4.1.3 from Steam. 

Any ideas?

**Comment by tayete** [comment]
The error is the one at the title obviously: "Could not resolve class "res://addons/iomjp94.yafsm/src/StackPlayer.gd"" in StateMachinePlayer.gd at (0,0).

**Comment by tayete** [comment]
Now I noticed 3 warnings that appeared at load time:

<img width="469" alt="yafsm" src="https://github.com/imjp94/gd-YAFSM/assets/45729291/32f4d2f5-3dd1-4705-8e9c-bd15f251d49f">

**Comment by tayete** [comment]
Even in another computer with a completely clean Godot + addon installment, it doesn't work anymore... really strange.

**Comment by rsubtil** [comment]
Seems that with Godot 4.1.3 the following lines start erroring out:
![image](https://github.com/imjp94/gd-YAFSM/assets/6501975/dae14c44-d738-4b25-b9ac-6f31e98f12ea)
The solution is to go through all the addon's scripts and remove such lines.

**Comment by amazingoomoo** [comment]
No, that doesn't work - it continues to throw error after error. I'm now getting a 

`Could not resolve an empty super class path "res://addons/imjp94.yafsm/scenes/FlowChart.gd"`

**Comment by amazingoomoo** [comment]
I've been through every script in the addon and commented out all of the super._init() lines in every script. But there are other scripts which connect to those scripts, and they all throw the above error about an empty super class.

**Comment by jktrctt** [comment]
I'm also having the same issue. The project stopped working for me when I moved to a new machine, with this same error.

**Comment by jktrctt** [comment]
FWIW, I was able to get the project running in Godot 4.1.1 - it breaks in 4.1.3

**Comment by mikerodd** [comment]
Once you remove all super.init calls that refer internal Godot classes, it works
![Capture d’écran du 2023-11-22 17-02-04](https://github.com/imjp94/gd-YAFSM/assets/4293086/ee0e7b60-c5da-4f36-b369-de8ceed744a4)

**Comment by amazingoomoo** [comment]
That simply doesn't work for me at all, I have methodically been through every script and removed every super_init call.

I still get errors such as in StateMachinePlayer.gd I get `Error at (0, 0): Could not resolve class "res://addons/imjp94.yafsm/src/StackPlayer.gd".`

**Comment by mikerodd** [comment]
@amazingoomoo : I created a pull request, does it work with this?

**Comment by amazingoomoo** [comment]
> @amazingoomoo : I created a pull request, does it work with this?

Hi I'm really sorry but I don't know what those words mean. I really don't understand GitHub and at this point I'm too afraid to ask! I don't know what a "commit" or a "pull request" is or even what a "git" is or what "github" is I just have no idea about any of this. Hopefully someone can request your pull and commit the git to the hub and then I can press the Fork Branches button and other made up words...

**Comment by mikerodd** [comment]
Yes I understand, i'm also struggling with github...
What you can do is go to my fork (which contains the fix) here : https://github.com/mikerodd/gd-YAFSM-4.1.3
download it as a zip file and replace the content of the addon corresponding directory (res://addons/imjp94.yafsm) in your project with this content

that should work too
