### ISSUE TITLE
Can't get it to work at all?

### ISSUE THREAD

**Issue by amazingoomoo** [imjp94/gd-YAFSM#75]
Hi, I'm following the instructions and creating the StateMachinePlayer node, and a "StateMachine" window appears at the bottom, but when I click it it's just grey. There's no grid, there's no controls, it's completely blank. I can't press any button anywhere to create a new state machine because there's no button. I also can't launch my scene with the plugin enabled because it throws several errors. 

It gives me this error in StateMachinePlayer.gd
`Line 0:Could not resolve class "res://addons/imjp94.yafsm/src/StackPlayer.gd"`

It also gives me this error in StackPlayer.gd
`Line 23:Cannot call the parent class' virtual function "_init()" because it hasn't been defined`

I'll be honest, I don't know what any of this means. The guide to this said it is "plug and play" which is great for me as I am just setting out. But I have failed at the first hurdle here.

Happy to supply my rather basic empty file if someone can tell me what file I would actually need to include.

**Comment by tayete** [comment]
Yep, that's the same issue I have opened recently. For some reason it has stopped working when it did perfectly, even though I installed it a couple of months ago and worked perfectly. Suddenly three days ago it started giving the message you mention, and the grid for the flowchart is completely grey.

**Comment by cplepel** [comment]
I also have this issue. I've been getting plugin.gd errors.

`  res://addons/imjp94.yafsm/plugin.gd:89 - Invalid set index 'state_machine' (on base: 'Control (StateMachineEditor.gd)') with value of type 'Nil'.
  res://addons/imjp94.yafsm/plugin.gd:113 - Invalid get index 'state_machine' (on base: 'Node (StateMachinePlayer.gd)').
  res://addons/imjp94.yafsm/plugin.gd:89 - Invalid set index 'state_machine' (on base: 'Control (StateMachineEditor.gd)') with value of type 'Nil'.
  res://addons/imjp94.yafsm/plugin.gd:113 - Invalid get index 'state_machine' (on base: 'Node (StateMachinePlayer.gd)').`

**Comment by cplepel** [comment]
Ok, I'm confirming that Issue #74 is seemingly the cause. It fails to parse the base class files, and this leads to errors across the entire thing.
