### ISSUE TITLE
Failed to migrate project from 4.1.2 to 4.2.1

### ISSUE THREAD

**Issue by 4ybaka** [imjp94/gd-YAFSM#78]
I had it work in 4.1.2 but after I updated to 4.2.1 it can't load resources anymore. 
![image](https://github.com/imjp94/gd-YAFSM/assets/507929/699100ab-2f71-47e8-9e18-1313175ae619)

Logs:
`Godot Engine v4.2.1.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:63 - Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
  res://addons/imjp94.yafsm/scenes/state_nodes/StateNode.gd:0 - Parse Error: Could not resolve class "res://addons/imjp94.yafsm/scenes/flowchart/FlowChartNode.gd".
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/imjp94.yafsm/scenes/state_nodes/StateNode.gd" with error "Parse error". (User)
  res://addons/imjp94.yafsm/scenes/transition_editors/TransitionLine.gd:0 - Parse Error: Could not resolve class "res://addons/imjp94.yafsm/scenes/flowchart/FlowChartLine.gd".
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/imjp94.yafsm/scenes/transition_editors/TransitionLine.gd" with error "Parse error". (User)
  res://addons/imjp94.yafsm/scenes/StateMachineEditor.gd:0 - Parse Error: Could not resolve class "res://addons/imjp94.yafsm/scenes/flowchart/FlowChart.gd".
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/imjp94.yafsm/scenes/StateMachineEditor.gd" with error "Parse error". (User)
  res://addons/imjp94.yafsm/src/StackPlayer.gd:23 - Parse Error: Cannot call the parent class' virtual function "_init()" because it hasn't been defined.
  res://addons/imjp94.yafsm/src/StateMachinePlayer.gd:0 - Parse Error: Could not resolve class "res://addons/imjp94.yafsm/src/StackPlayer.gd".
  res://addons/imjp94.yafsm/src/StateDirectory.gd:19 - Parse Error: Cannot call the parent class' virtual function "_init()" because it hasn't been defined.
  res://addons/imjp94.yafsm/src/states/State.gd:22 - Parse Error: Cannot call the parent class' virtual function "_init()" because it hasn't been defined.
  res://addons/imjp94.yafsm/src/states/StateMachine.gd:0 - Parse Error: Could not resolve class "State".
  res://addons/imjp94.yafsm/src/transitions/Transition.gd:19 - Parse Error: Cannot call the parent class' virtual function "_init()" because it hasn't been defined.
  res://addons/imjp94.yafsm/src/conditions/Condition.gd:13 - Parse Error: Cannot call the parent class' virtual function "_init()" because it hasn't been defined.
  res://addons/imjp94.yafsm/src/conditions/ValueCondition.gd:0 - Parse Error: Could not resolve class "Condition".
  res://addons/imjp94.yafsm/src/conditions/Condition.gd:13 - Parse Error: Cannot call the parent class' virtual function "_init()" because it hasn't been defined.
  res://addons/imjp94.yafsm/src/conditions/ValueCondition.gd:-1 - Compile Error: 
  res://addons/imjp94.yafsm/src/conditions/BooleanCondition.gd:-1 - Compile Error: 
  res://addons/imjp94.yafsm/YAFSM.gd:-1 - Compile Error: 
  res://addons/imjp94.yafsm/scenes/transition_editors/TransitionEditor.gd:33 - Parse Error: Cannot call the parent class' virtual function "_init()" because it hasn't been defined.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/imjp94.yafsm/scenes/transition_editors/TransitionEditor.gd" with error "Parse error". (User)
  res://addons/imjp94.yafsm/src/transitions/Transition.gd:19 - Parse Error: Cannot call the parent class' virtual function "_init()" because it hasn't been defined.
  res://addons/imjp94.yafsm/scenes/transition_editors/TransitionInspector.gd:-1 - Compile Error: 
  res://addons/imjp94.yafsm/src/states/State.gd:22 - Parse Error: Cannot call the parent class' virtual function "_init()" because it hasn't been defined.
  res://addons/imjp94.yafsm/scenes/state_nodes/StateInspector.gd:-1 - Compile Error: 
  res://addons/imjp94.yafsm/src/states/State.gd:22 - Parse Error: Cannot call the parent class' virtual function "_init()" because it hasn't been defined.
  res://addons/imjp94.yafsm/src/transitions/Transition.gd:19 - Parse Error: Cannot call the parent class' virtual function "_init()" because it hasn't been defined.
  res://addons/imjp94.yafsm/src/states/StateMachine.gd:-1 - Compile Error: 
  res://addons/imjp94.yafsm/src/StackPlayer.gd:23 - Parse Error: Cannot call the parent class' virtual function "_init()" because it hasn't been defined.
  res://addons/imjp94.yafsm/src/states/State.gd:22 - Parse Error: Cannot call the parent class' virtual function "_init()" because it hasn't been defined.
  res://addons/imjp94.yafsm/src/StateMachinePlayer.gd:-1 - Compile Error: 
  res://addons/imjp94.yafsm/plugin.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/imjp94.yafsm/plugin.gd" with error "Compilation failed". (User)
  res://addons/imjp94.yafsm/plugin.gd:31 - Invalid get index 'selection_stylebox' (on base: 'Control (StateMachineEditor.gd)').
  modules/gdscript/gdscript.cpp:136 - Parameter "p_script->implicit_initializer" is null.
  modules/gdscript/gdscript.cpp:136 - Parameter "p_script->implicit_initializer" is null.
  modules/gdscript/gdscript.cpp:136 - Parameter "p_script->implicit_initializer" is null.
  res://addons/imjp94.yafsm/src/conditions/ValueCondition.gd:73 - Invalid call. Nonexistent function 'display_string'.
  modules/gdscript/gdscript.cpp:136 - Parameter "p_script->implicit_initializer" is null.
  res://addons/imjp94.yafsm/src/conditions/ValueCondition.gd:73 - Invalid call. Nonexistent function 'display_string'.
  modules/gdscript/gdscript.cpp:136 - Parameter "p_script->implicit_initializer" is null.
  modules/gdscript/gdscript.cpp:136 - Parameter "p_script->implicit_initializer" is null.
  Parent node is busy setting up children, `add_child()` failed. Consider using `add_child.call_deferred(child)` instead.
  Parent node is busy setting up children, `add_child()` failed. Consider using `add_child.call_deferred(child)` instead.
Add Autoload
INFO [17/12/2023 10:30:20] setting log level {"level":"debug"}
  res://addons/imjp94.yafsm/scenes/flowchart/FlowChart.gd:67 - Parse Error: Cannot call the parent class' virtual function "_init()" because it hasn't been defined.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/imjp94.yafsm/scenes/flowchart/FlowChart.gd" with error "Parse error". (User)
  res://addons/imjp94.yafsm/src/StackPlayer.gd:23 - Parse Error: Cannot call the parent class' virtual function "_init()" because it hasn't been defined.
  res://addons/imjp94.yafsm/src/debugger/StackPlayerDebugger.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/imjp94.yafsm/src/debugger/StackPlayerDebugger.gd" with error "Compilation failed". (User)
  modules/gdscript/gdscript.cpp:136 - Parameter "p_script->implicit_initializer" is null.
  modules/gdscript/gdscript.cpp:136 - Parameter "p_script->implicit_initializer" is null.
  modules/gdscript/gdscript.cpp:136 - Parameter "p_script->implicit_initializer" is null.
  res://addons/imjp94.yafsm/src/conditions/ValueCondition.gd:73 - Invalid call. Nonexistent function 'display_string'.
  modules/gdscript/gdscript.cpp:136 - Parameter "p_script->implicit_initializer" is null.
  res://addons/imjp94.yafsm/src/conditions/ValueCondition.gd:73 - Invalid call. Nonexistent function 'display_string'.
  modules/gdscript/gdscript.cpp:136 - Parameter "p_script->implicit_initializer" is null.
  modules/gdscript/gdscript.cpp:136 - Parameter "p_script->implicit_initializer" is null.
`

**Comment by dartinger** [comment]
I have the same issue with brand new project.

**Comment by dartinger** [comment]
@4ybaka You can use the plugin from the master-branch (Download per ZIP). This works fine for me (Godot v4.2.1).
If you need to install it from the asset lib, you need to wait for the next patch. 

@imjp94 Issue can be closed.

**Comment by imjp94** [comment]
My bad, always forgot to submit to Asset Library =P

Just made a release for 0.6.2 and submitted to Asset Library
