### ISSUE TITLE
Not compatible with Godot 4.2

### ISSUE THREAD

**Issue by QbieShay** [imjp94/gd-YAFSM#79]
Hey! 

Just downloaded the addon for my project and it doesn't seem to work for Godot 4.2

getting these errors 

```
res://addons/imjp94.yafsm/plugin.gd:89 - Invalid set index 'state_machine' (on base: 'Control (StateMachineEditor.gd)') with value of type 'Nil'.
  res://addons/imjp94.yafsm/plugin.gd:114 - Invalid set index 'state_machine_player' (on base: 'Control (StateMachineEditor.gd)') with value of type 'Node (StateMachinePlayer.gd)'.
  res://addons/imjp94.yafsm/plugin.gd:117 - Invalid set index 'state_machine_player' (on base: 'Control (StateMachineEditor.gd)') with value of type 'Nil'.
  ```

**Comment by imjp94** [comment]
I assume you downloaded from Godot Asset Library which is outdated, see #78 

I have submitted an update to Asset Library, but it haven't got approved yet.
As a workaround for now, you can download straight away from the repo or from the [latest release 0.6.2](https://github.com/imjp94/gd-YAFSM/releases/tag/0.6.2)

**Comment by QbieShay** [comment]
Thank you!!
